DIRECTORIES:
  API_REPO: /vagrant/repo/busineme-api
  WEB_REPO: /vagrant/repo/busineme-web
APPLICATION:
  WEB_REPOSITORY: https://github.com/Busineme/BusinemeWeb.git
  API_REPOSITORY: https://github.com/Busineme/BusinemeAPI.git
  API_URL: http://10.10.10.2:8080/api/v1/
  SECRET_KEY: secret-key
DATABASE:
  NAME: busineme
  USER: busineme
  PASSWORD: 1234
